version: '3.8'

services:
  # Backend Service (hianime-api)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hianime-backend
    restart: unless-stopped
    env_file:
      - ./backend.env
    depends_on:
      - redis
    networks:
      - hianime-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    expose:
      - "3030"

  # Frontend Service (watanuki)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hianime-frontend
    restart: unless-stopped
    env_file:
      - ./frontend.env
    depends_on:
      - backend
    networks:
      - hianime-network
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis Service for Caching
  redis:
    image: redis:7-alpine
    container_name: hianime-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - hianime-network
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: hianime-nginx
    restart: unless-stopped
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - hianime-network
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  hianime-network:
    driver: bridge

volumes:
  redis_data:
    driver: local